### ISSUE TITLE
UPDATE

### ISSUE THREAD

**Issue by meiyuluohua** [morganwall/War-Thunder-Offset-Dumper#2]
When will you update again and I would like to get another offset

**Comment by morganwall** [comment]
Hey, I haven't done anything in the way of reversing War Thunder lately, though I'll push an update to this once I do.

**Comment by meiyuluohua** [comment]
Thank you very much for reading my review in your busy schedule, looking forward to your next update

**Comment by morganwall** [comment]
Looks like someone else beat me to it. I've merged their pull request with the main branch, should be working now.

**Comment by meiyuluohua** [comment]
I would like to get the following offset
![image](https://user-images.githubusercontent.com/112864022/190305974-aeba3359-565c-4e0f-a6dd-39a61de1fc60.png)
