### ISSUE TITLE
I would like to get the following offset

### ISSUE THREAD

**Issue by meiyuluohua** [morganwall/War-Thunder-Offset-Dumper#4]
![image](https://user-images.githubusercontent.com/112864022/190307344-903ddcf0-6889-4a9f-8e2a-28c5006e23b9.png)

**Comment by monkrel** [comment]
😳make it yourself. This dumper gives you main offsets for searching, just add new signature to code when you will find it

**Comment by meiyuluohua** [comment]
> 😳自己动手。这个转储器为您提供了用于搜索的主要偏移量，只需在找到它时向代码添加新签名即可

CE Unable to attach

**Comment by monkrel** [comment]
disable EAC

**Comment by meiyuluohua** [comment]
> disable EAC

i can't

**Comment by morganwall** [comment]
> > disable EAC
> 
> i can't

Included in the readme is how to launch the game without EAC, allowing you to attach CE, ReClass, or anything else.

**Comment by morganwall** [comment]
As for said requested offsets, I may add some of them if I do get back into reversing the game. As I expressed before, I'm been mostly busy lately due to Uni.

**Comment by monkrel** [comment]
I have more than half of them, if you need it - i can share

**Comment by morganwall** [comment]
> I have more than half of them, if you need it - i can share

Yeah that'd be great. Either just drop them here, or if you have sigs just make a pull request. Thank you 👍🏻

**Comment by meiyuluohua** [comment]
> 至于上述请求的偏移量，如果我确实重新开始逆转游戏，我可能会添加其中一些。正如我之前所说，由于Uni，我最近大部分时间都很忙。
Thank you very much, looking forward to your next update

**Comment by meiyuluohua** [comment]
> 我有一半以上，如果你需要它 - 我可以分享

thank you very much

**Comment by meiyuluohua** [comment]
> > > 禁用电子可编程逻辑控制器
> > 
> > 
> > 我不能
> 
> 自述文件中包含如何在没有 EAC 的情况下启动游戏，允许您附加 CE、ReClass 或其他任何内容。

Disable EAC to open the game, the game crashes when CE is attached

**Comment by morganwall** [comment]
> > > > 禁用电子可编程逻辑控制器
> > > 
> > > 
> > > 我不能
> > 
> > 
> > 自述文件中包含如何在没有 EAC 的情况下启动游戏，允许您附加 CE、ReClass 或其他任何内容。
> 
> Disable EAC to open the game, the game crashes when CE is attached

Weird. I'll take a look later today.

**Comment by meiyuluohua** [comment]
Program crashes instantly

**Comment by monkrel** [comment]
wdym?
![image](https://user-images.githubusercontent.com/84017229/190574378-5ec20ef2-c387-42ec-ae57-5e442184982a.png)

**Comment by morganwall** [comment]
Maybe the game differs depending on region, or maybe it could be crashing due to system language. Completely speculative though.

**Comment by morganwall** [comment]
> Program crashes instantly

After going testing it for myself, it seems I managed to break one of the sigs with one of my commits. I've updated it now, and it should work as expected.

**Comment by meiyuluohua** [comment]
> 

thanks

**Comment by morganwall** [comment]
Due to the issue being resolved now, I will close this issue. I will in turn create a new issue for requesting new signatures to be added.
