### ISSUE TITLE
Signature/Offset Requests

### ISSUE THREAD

**Issue by morganwall** [morganwall/War-Thunder-Offset-Dumper#5]
# Purpose
The purpose of this issue is to allow people to request signatures to be added into the dumper, and or to just request current offsets.

**Comment by meiyuluohua** [comment]
![image](https://user-images.githubusercontent.com/112864022/190851401-a025ef33-e944-4200-a063-dbcc1680353b.png)

**Comment by morganwall** [comment]
- playerListOffset: ``` (aces.exe + 0x41E6DC8), 0x8 ```
- playerCountOffset: ``` (aces.exe + 0x41E6DC8 + 0x8) ```
- playerNameOffset ``` (aces.exe + 0x41E6DC8), 0x8, currentEntity, 0xB0 ```
- entityUnitOffset ``` (aces.exe + 0x41E6DC8), 0x8, currentEntity, 0x710 ```
- unitCoordsOffset ``` (aces.exe + 0x41E6DC8), 0x8, currentEntity, 0x710, 0xA98 ```
- teamIdOffset ``` (aces.exe + 0x41E6DC8), 0x8, currentEntity, 0x710, 0x1298 ```
I don't have signatures for these currently, though I may at a later date.

**Comment by meiyuluohua** [comment]
bulletMuzzleVelocity

**Comment by morganwall** [comment]
> bulletMuzzleVelocity

I'll take a look later today if I'm not too busy, though I've not looked into the bullet struct before.

**Comment by JFdevel** [comment]
pls help

![image](https://user-images.githubusercontent.com/39263181/202507750-a532c4a7-c6e4-4ebb-ac23-a35db083032e.png)

**Comment by morganwall** [comment]
> pls help
> 
> ![image](https://user-images.githubusercontent.com/39263181/202507750-a532c4a7-c6e4-4ebb-ac23-a35db083032e.png)

Please don't ask for help in this issue, this issue is meant for people to ask and share signatures/offsets.
Feel free to open a new issue though.
