### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by KABO1488** [morganwall/War-Thunder-Offset-Dumper#8]
in another issue there was a question about an error, but there was no answer. Can you help with this problem?
![202507750-a532c4a7-c6e4-4ebb-ac23-a35db083032e](https://user-images.githubusercontent.com/104678564/219195510-d9a48d84-2829-45ea-85dd-707bdc7c5d9c.png)

**Comment by morganwall** [comment]
Have you updated the signatures?
They are super outdated as I've not worked on this in ages, so it's probably trying to read from an invalid memory location.

**Comment by morganwall** [comment]
Due to a lack of engagement, I'm gonna close the issue.
